{% set name = "reindent" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59aeb8fbc16e45686f65df23b91896a17eb14ace7a7546860f50d2bb5ec4c9c0

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - reindent = reindent:main

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - reindent
  commands:
    - echo "pass" | reindent

about:
  home: https://pypi.python.org/pypi/reindent
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: 'README.md'
  summary: reindent script by Tim Peters
  description: |
    Reindent python cleanup script
    Change Python (.py) files to use 4-space indents and no hard
    tab characters.  Also trim excess spaces and tabs from ends of
    lines, and remove empty lines at the end of files.  Also
    ensure the last line ends with a newline.

extra:
  recipe-maintainers:
    - anthchirp
    - smithsp
